# Generated by Django 3.2 on 2025-03-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField()),
                ('candidate_required_location', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
