# Generated by Django 5.0.6 on 2025-03-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0003_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='Last_Login_Date',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='Last_Login_Time',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='Message',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='No_Of_Times_Login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='Otp_Num',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='Otp_Status',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_contact',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_subject',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(help_text='user_password', max_length=50),
        ),
    ]
